### ISSUE TITLE
[Live Stream] 直播流组件处理报错

### ISSUE THREAD

**Issue by limjoe** [tnfe/FFCreatorLite#12]
作者增加了对 Live Stream 的支持后，example/live.js 处理时 ffmpeg 会报错

此外，从日志来看似乎也没有增加 audio
commit id: `e0b8df2590ab118545cad7241636f0dbbe8be1fe `

报错日志:
```
FFCreatorLite start
single: ffmpeg -loop 1 -i /Users/joe/Workspace/VMS/FFCreatorLite/examples/assets/imgs/wallp/06.jpeg -i  rtmp://xxxx -loop 1 -i /Users/joe/Workspace/VMS/FFCreatorLite/examples/assets/imgs/06.png -filter_complex color=c=#9980fa:d=17:size=700*500[background2-0];[background2-0][0:v]overlay=x=50:y=50[image1-1];[1:v]scale=iw*0.3:ih*0.3[live1-1];[live1-1]fade=type=in:st=3.5:d=2.5:color=black:alpha=1[live1-2];[image1-1][live1-2]overlay=x='if(between(t,3.5,6),200-200*(t-3.5)/2.5+100*pow((t-3.5)/2.5,2),100)':y='if(between(t,3.5,6),100+0*(t-3.5)/2.5-0*pow((t-3.5)/2.5,2),100)':enable='between(t,3.5,99999)'[live1-3];[2:v]fade=type=in:st=0:d=1.5:color=black:alpha=1[image2-1];[live1-3][image2-1]overlay=x='if(between(t,0,1.5),-180+200*t/1.5-100*pow(t/1.5,2),-80)':y='if(between(t,0,1.5),80+0*t/1.5-0*pow(t/1.5,2),80)'[image2-2];[image2-2]drawtext=bordercolor=#000000:borderw=5:fontcolor=#ffffff:fontfile=/Users/joe/Workspace/VMS/FFCreatorLite/examples/assets/font/scsf.ttf:fontsize=42:text=FFLive案例:x=230:y=100:eble='between(t,0,99999)'[text1-1] -map [text1-1] -r 24 -map 0 -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -f flv rtmp://192.168.3.2/live/h264Stream
==============
Error: ffmpeg exited with code 1: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 -- 
Conversion failed!

    at ChildProcess.<anonymous> (/Users/joe/Workspace/VMS/FFCreatorLite/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
FFCreatorLite error:: 
 Error: ffmpeg exited with code 1: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 -- 
Conversion failed!
```

**Comment by drawcall** [comment]
Oh, maybe you can modify and submit a pr. Maybe it's a problem with ffmpeg parameters.
 I have too little time recently. Sorry

**Comment by limjoe** [comment]
Thanks,
ok, 我改完提交一个 PR

**Comment by limjoe** [comment]
作者的代码没有什么大问题了，目前卡在了将结果再次推流到流媒体服务器上，目前我调试并 google 了许久，以下这个报错一直没找到解决办法

1. 使用以下命令行将结果保存为 mp4, 能正常保存并能播放
2. 使用以下命令行将结果推流到 rtmp 流媒体服务器，会报错

命令行:
```
ffmpeg -loop 1 -i /Users/joe/Workspace/VMS/FFCreatorLite/lib/assets/blank.png -loop 1 -i /Users/joe/Workspace/VMS/FFCreatorLite/examples/assets/imgs/wallp/06.jpeg -i "https://play-beijing-10010-01-alias-02.xxxx.com/live/K2ngoUCE0KBo.flv?auth_sign=1632382646740-0-03C80017C7D95C23-8ba775d8fdbe6a776ad9f2ab4946b6358f235a29805ee1c247b4d09c51fd430f" -loop 1 -i /Users/joe/Workspace/VMS/FFCreatorLite/examples/assets/imgs/06.png -stream_loop -1 -i /Users/joe/Workspace/VMS/FFCreatorLite/examples/assets/audio/03.wav -filter_complex "color=c=#9980fa:d=17:size=700*500[background2-0];[background2-0][0:v]overlay=x=-10:y=0[image1-1];[image1-1][1:v]overlay=x=50:y=50[image2-1];[2:v]scale=iw*0.3:ih*0.3[live1-1];[live1-1]fade=type=in:st=3.5:d=2.5:color=black:alpha=1[live1-2];[image2-1][live1-2]overlay=x='if(between(t,3.5,6),200-200*(t-3.5)/2.5+100*pow((t-3.5)/2.5,2),100)':y='if(between(t,3.5,6),100+0*(t-3.5)/2.5-0*pow((t-3.5)/2.5,2),100)':enable='between(t,3.5,99999)'[live1-3];[3:v]fade=type=in:st=0:d=1.5:color=black:alpha=1[image3-1];[live1-3][image3-1]overlay=x='if(between(t,0,1.5),-180+200*t/1.5-100*pow(t/1.5,2),-80)':y='if(between(t,0,1.5),80+0*t/1.5-0*pow(t/1.5,2),80)'[image3-2];[image3-2]drawtext=bordercolor=#000000:borderw=5:fontcolor=#ffffff:fontfile=/Users/joe/Workspace/VMS/FFCreatorLite/examples/assets/font/scsf.ttf:fontsize=42:text=FFLive案例:x=230:y=100:enable='between(t,0,99999)'[text1-1]" -map "[text1-1]" -r 24 -map 0 -hide_banner -map_metadata -1 -map_chapters -1 -c copy -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -c:a copy -shortest -map 4:a -c:a aac -shortest -f flv rtmp://192.168.3.2/live/h264Stream

```
处理日志
```
Input #0, png_pipe, from '/Users/joe/Workspace/VMS/FFCreatorLite/lib/assets/blank.png':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: png, rgba(pc), 10x10 [SAR 2835:2835 DAR 1:1], 25 fps, 25 tbr, 25 tbn, 25 tbc
Input #1, flv, from 'https://play-beijing-10010-01-alias-02.down.com/live/K2ngoUCE0KBo.flv?auth_sign=1632382646740-0-03C80017C7D95C23-8ba775d8fdbe6a776ad9f2ab4946b6358f235a29805ee1c247b4d09c51fd430f':
  Duration: N/A, start: 0.020000, bitrate: N/A
    Stream #1:0: Audio: aac (Main), 16000 Hz, mono, fltp
    Stream #1:1: Video: h264 (Baseline), yuvj420p(pc, bt709, progressive), 1920x1080, 1k tbr, 1k tbn
[mp3 @ 0x7ff6790e0800] Estimating duration from bitrate, this may be inaccurate
Input #2, mp3, from '/Users/joe/Downloads/music.mp3':
  Metadata:
    TSS             : Logic Pro X 10.6.2
    iTunNORM        :  0000005E 0000005D 000009C1 000009C2 00007B78 00007B78 0000651F 000062FC 00007B5E 00007B5E
    iTunSMPB        :  00000000 00000210 00000A5A 000000000070ED16 00000000 00665800 00000000 00000000 00000000 00000000 00000000 00000000
    TKE             : Dm
    artist          : Balkan Jingles
    TBP             : 71
    title           : Let's make this a song
    album           : Shall we Move On?
    TCM             : Georgi Milev - Anstasis Sarakatsanos
    date            : 2021-06-13 13:17
  Duration: 00:02:47.89, start: 0.000000, bitrate: 320 kb/s
    Stream #2:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s
Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 2, only the last option '-c:a aac' will be used.
Stream mapping:
  Stream #0:0 (png) -> overlay:overlay (graph 0)
  Stream #1:1 (h264) -> scale (graph 0)
  overlay (graph 0) -> Stream #0:0 (libx264)
  Stream #0:0 -> #0:1 (png (native) -> h264 (libx264))
  Stream #2:0 -> #0:2 (mp3 (mp3float) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0x7ff67882ba00] using SAR=1/1
[libx264 @ 0x7ff67882ba00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7ff67882ba00] profile Main, level 1.0, 4:2:0, 8-bit
[libx264 @ 0x7ff67882ba00] 264 - core 160 r3011M cde9a93 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=1 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=24 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=20.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[flv @ 0x7ff679010e00] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[swscaler @ 0x7ff67cc0d000] deprecated pixel format used, make sure you did set range correctly
[libx264 @ 0x7ff6790cfa00] using SAR=1/1
[libx264 @ 0x7ff6790cfa00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7ff6790cfa00] profile Main, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x7ff6790cfa00] 264 - core 160 r3011M cde9a93 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=24 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=20.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[flv @ 0x7ff67a80e000] at most one video stream is supported in flv
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:2 --

```

**Comment by limjoe** [comment]
通过生成 mp4 的日志发现，是因为生成了 2 个 video stream 通道导致了 flv 推流失败
```
[libx264 @ 0x7fe772878800] 264 - core 160 r3011M cde9a93 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=24 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=20.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'test001.mp4':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p(progressive), 700x500 [SAR 1:1 DAR 7:5], q=-1--1, 24 fps, 12288 tbn, 24 tbc
    Metadata:
      encoder         : Lavc58.91.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
    Stream #0:1: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p(progressive), 10x10 [SAR 1:1 DAR 1:1], q=-1--1, 24 fps, 12288 tbn, 24 tbc
    Metadata:
      encoder         : Lavc58.91.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
    Stream #0:2: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc58.91.100 aac
[Parsed_color_0 @ 0x7fe771de4540] EOF timestamp not reliable:15.04 bitrate= 418.3kbits/s dup=0 drop=30 speed=0.991x    
[mp4 @ 0x7fe772871600] Starting second pass: moving the moov atom to the beginning of the file drop=400 speed=0.759x    
frame= 4850 fps= 18 q=-1.0 Lq=25.0 size=   12358kB time=00:03:22.00 bitrate= 501.2kbits/s dup=0 drop=400 speed=0.764x 
```

**Comment by limjoe** [comment]
搞定了，我整理下代码提交 MR

**Comment by drawcall** [comment]
great

**Comment by limjoe** [comment]
我提交了 MR ，麻烦作者看看，此外去掉 '-map 0' 默认配置，稍微有些不优雅，作者可以再次重构一下

**Comment by drawcall** [comment]
Already released Great job

**Comment by limjoe** [comment]
Thanks for your great repo.

**Comment by limjoe** [comment]
还有个问题，我一直没找到怎么关闭 liveStream 的任务，通过 creater.destroy() 函数也无法关闭，或者作者你告诉我能否获取任务中生成的 ffmpeg 命令，如果我能获取 ffmpeg 命令，我通过 spawn 来执行 ffmpeg ，可以通过 进程的 kill 函数来关闭 ffmpeg 进程

**Comment by drawcall** [comment]
Please download the latest version and use ffcreator.destroy

**Comment by limjoe** [comment]
酷，不过我刚也找到了解决办法

在 scene.js 的 destroy 方法中增加 this.command.kill();

**Comment by drawcall** [comment]
You can write any os projects based on ffcreator, look forward to
